# Generated by Django 5.1.1 on 2024-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('pages', models.PositiveIntegerField()),
                ('languages', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
